### ISSUE TITLE
NotFoundError: Failed to create a directory: ./models\variables; No such file or directory

### ISSUE THREAD

**Issue by ouening** [leimao/Frozen_Graph_TensorFlow#1]
OS: Win10
python: 3.7
Tensorflow: 2.1

Hi, when I ran the `train.py` file, I got an error:
`NotFoundError: Failed to create a directory: ./models\variables; No such file or directory`
How can I fix it?

**Comment by leimao** [comment]
Please try to use Docker container as I described in the README, because it is almost impossible to troubleshoot for each specific environment. An educational guess to your problem is that Windows is blocking your writing to the hard drive. Avoid using Windows if you are doing machine learning, unless it is extremely necessary.

**Comment by leimao** [comment]
I think it is due to the difference between file path formats in Linux and Windows. Note the difference between `/` and `\`. Just use the Docker container please.

**Comment by leimao** [comment]
Consider it resolved.
